---
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/HibiscusSyriacusExplorer
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/HibiscusSyriacusExplorer/deploy.sh
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 180
      runas: ubuntu

# test log 2
