---

name: Static Code Analyze

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  static_code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.HEAD_REF }}

      - name: Setup python environment
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4.0.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install black isort mypy fastapi

      - name: Run Black
        run: black . --check

      - name: Run Isort
        run: isort . --check --diff

      # - name: Run Mypy
      #   run: mypy .

      - name: Run unittest
        run: python -m unittest discover -s ./test -p '*_test.py' -v
